import type { ServiceRate } from "./profileOptions";

export type PublicProfile = {
  userId: string;
  displayName: string;
  age: number;
  gender: "MALE" | "FEMALE" | "NONBINARY";
  country: string;
  state: string;
  city: string;
  bio: string;
  avatarUrl: string;
  photos: string[];
  interests: string[];
  ethnicity: string;
  bodyBuild: string;
  education: string;
  smoking: string;
  orientation: string;
  services: ServiceRate[];
  verified: boolean;
  boosted: boolean;
  online: boolean;
  availableToday: boolean;
  live: boolean;
  profileViews: number;
  joinedAt: Date;
};

const service = (
  name: string,
  outcallRate: number,
  incallRate: number | null = null
): ServiceRate => ({ name, incallRate, outcallRate, enabled: true });

const GALLERY_PHOTOS = [
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=82",
  "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1000&q=82",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=82",
  "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=82",
  "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1000&q=82",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=82",
];

function gallery(offset: number) {
  return Array.from({ length: 3 }, (_, index) => GALLERY_PHOTOS[(offset + index) % GALLERY_PHOTOS.length]);
}

export const DEMO_PROFILES: PublicProfile[] = [
  {
    userId: "demo-amara",
    displayName: "Amara",
    age: 24,
    gender: "FEMALE",
    country: "Nigeria",
    state: "Lagos",
    city: "Lekki",
    bio: "Creative producer, live music regular, and always looking for the next great restaurant.",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(0),
    interests: ["Music", "Foodie", "Travel"],
    ethnicity: "Black / African",
    bodyBuild: "Curvy",
    education: "BSc",
    smoking: "No",
    orientation: "Straight",
    services: [service("Erotic massage", 90000, 75000), service("Dinner Dates", 110000, 85000), service("Role Play & Fantasy", 160000, 130000), service("GFE (Girlfriend experience)", 210000, 175000)],
    verified: true,
    boosted: true,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 8421,
    joinedAt: new Date("2026-07-10"),
  },
  {
    userId: "demo-zainab",
    displayName: "Zainab",
    age: 25,
    gender: "FEMALE",
    country: "Nigeria",
    state: "Federal Capital Territory",
    city: "Wuse",
    bio: "Architect by day, film photographer after hours. Quiet plans and good conversation win.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(2),
    interests: ["Art", "Travel", "Movies"],
    ethnicity: "Black / African",
    bodyBuild: "Slim",
    education: "Masters",
    smoking: "No",
    orientation: "Straight",
    services: [service("Massage", 70000, 55000), service("Dinner Dates", 95000), service("Tantric Massage", 125000, 100000), service("Event companion", 140000)],
    verified: true,
    boosted: false,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 6104,
    joinedAt: new Date("2026-07-08"),
  },
  {
    userId: "demo-tunde",
    displayName: "Tunde",
    age: 28,
    gender: "MALE",
    country: "Nigeria",
    state: "Lagos",
    city: "Ikeja",
    bio: "Product designer, weekend runner, and firm believer that playlists are a love language.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(1),
    interests: ["Tech", "Music", "Art"],
    ethnicity: "Black / African",
    bodyBuild: "Athletic",
    education: "BSc",
    smoking: "Occasionally",
    orientation: "Straight",
    services: [service("Massage", 65000, 50000), service("Couples", 140000, 110000), service("Dinner Dates", 80000), service("Full evening", 160000)],
    verified: true,
    boosted: true,
    online: false,
    availableToday: false,
    live: false,
    profileViews: 5740,
    joinedAt: new Date("2026-06-30"),
  },
  {
    userId: "demo-bisi",
    displayName: "Bisi",
    age: 26,
    gender: "FEMALE",
    country: "Nigeria",
    state: "Oyo",
    city: "Ibadan",
    bio: "Gallery weekends, gym mornings, and conversations that skip the small talk.",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(4),
    interests: ["Art", "Fashion", "Foodie"],
    ethnicity: "Black / African",
    bodyBuild: "Athletic",
    education: "BSc",
    smoking: "No",
    orientation: "Bisexual",
    services: [service("Erotic massage", 85000, 70000), service("Erotic Spanking (giving)", 120000, 95000), service("GFE (Girlfriend experience)", 175000, 145000)],
    verified: false,
    boosted: false,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 3902,
    joinedAt: new Date("2026-07-14"),
  },
  {
    userId: "demo-emeka",
    displayName: "Emeka",
    age: 29,
    gender: "MALE",
    country: "Nigeria",
    state: "Enugu",
    city: "New Haven",
    bio: "Engineer, football fan, and a surprisingly capable Sunday cook.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(3),
    interests: ["Tech", "Foodie", "Music"],
    ethnicity: "Black / African",
    bodyBuild: "Average",
    education: "Masters",
    smoking: "No",
    orientation: "Straight",
    services: [service("Massage", 70000, 55000), service("Prostate Massage", 105000, 85000), service("Role Play & Fantasy", 135000, 110000)],
    verified: true,
    boosted: false,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 4891,
    joinedAt: new Date("2026-07-02"),
  },
  {
    userId: "demo-chiamaka",
    displayName: "Chiamaka",
    age: 27,
    gender: "FEMALE",
    country: "Nigeria",
    state: "Rivers",
    city: "Old GRA",
    bio: "Brand strategist, beach person, and always down for a spontaneous weekend away.",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(0),
    interests: ["Travel", "Nightlife", "Fashion"],
    ethnicity: "Black / African",
    bodyBuild: "Slim",
    education: "BSc",
    smoking: "Occasionally",
    orientation: "Straight",
    services: [service("GFE (Girlfriend experience)", 220000, 180000), service("Dinner Dates", 125000), service("Role Play & Fantasy", 170000, 140000), service("Weekend companion", 480000)],
    verified: true,
    boosted: true,
    online: false,
    availableToday: false,
    live: false,
    profileViews: 9330,
    joinedAt: new Date("2026-06-27"),
  },
  {
    userId: "demo-ibrahim",
    displayName: "Ibrahim",
    age: 30,
    gender: "MALE",
    country: "Nigeria",
    state: "Kano",
    city: "Nassarawa",
    bio: "Architect, coffee loyalist, and collector of very specific travel recommendations.",
    avatarUrl: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(1),
    interests: ["Travel", "Art", "Tech"],
    ethnicity: "Black / African",
    bodyBuild: "Average",
    education: "Masters",
    smoking: "No",
    orientation: "Straight",
    services: [service("Massage", 65000, 50000), service("Couples", 150000, 120000), service("Dinner Dates", 85000)],
    verified: false,
    boosted: false,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 3147,
    joinedAt: new Date("2026-07-11"),
  },
  {
    userId: "demo-ngozi",
    displayName: "Ngozi",
    age: 28,
    gender: "FEMALE",
    country: "Nigeria",
    state: "Lagos",
    city: "Victoria Island",
    bio: "Lawyer, bookshop regular, and enthusiastic reviewer of every new spot in town.",
    avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(4),
    interests: ["Books", "Foodie", "Nightlife"],
    ethnicity: "Black / African",
    bodyBuild: "Curvy",
    education: "BSc",
    smoking: "No",
    orientation: "Straight",
    services: [service("Erotic massage", 110000, 90000), service("Hand Job", 95000, 75000), service("GFE (Girlfriend experience)", 240000, 200000), service("Dinner Dates", 120000)],
    verified: true,
    boosted: false,
    online: false,
    availableToday: false,
    live: false,
    profileViews: 7235,
    joinedAt: new Date("2026-07-05"),
  },
  {
    userId: "demo-kelechi",
    displayName: "Kelechi",
    age: 31,
    gender: "MALE",
    country: "Nigeria",
    state: "Rivers",
    city: "Port Harcourt",
    bio: "Chef, live-show regular, and usually the person organizing the group trip.",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=1200&q=86",
    photos: gallery(2),
    interests: ["Foodie", "Music", "Travel"],
    ethnicity: "Black / African",
    bodyBuild: "Athletic",
    education: "Diploma",
    smoking: "Occasionally",
    orientation: "Straight",
    services: [service("Massage", 75000, 60000), service("Prostate Massage", 115000, 90000), service("Role Play & Fantasy", 150000, 120000), service("Weekend companion", 380000)],
    verified: true,
    boosted: true,
    online: true,
    availableToday: true,
    live: true,
    profileViews: 6688,
    joinedAt: new Date("2026-06-24"),
  },
];

export function findDemoProfile(userId: string) {
  return DEMO_PROFILES.find((profile) => profile.userId === userId) ?? null;
}
